name: Automatic Merge

on:
  pull_request:
    types: [opened, labeled, synchronize]
    branches: [master]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Depandabot and has label
        id: check_conditions
        if: github.event_name == 'pull_request' && github.event.pull_request
        run: |
          const pr = github.event.pull_request;
          const labels = pr.labels.map(label => label.name);
          const isDepandabot = pr.user.login === 'dependabot[bot]';
          const shouldMerge = isDepandabot && labels.includes('automatic-merge');

          echo "${shouldMerge ? 'Depandabot pull request with automatic-merge label detected.' : 'Not a Depandabot pull request with automatic-merge label. Exiting.'}"
          echo "::set-output name=should_merge::${shouldMerge}"
          if (shouldMerge) {
            echo "::set-env name=PR_URL::${pr.html_url}"
          }

      - name: Merge Pull Request
        if: steps.check_conditions.outputs.should_merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ env.PR_URL }}
        run: |
          gh pr merge --merge --auto "${PR_URL}"
