name: Automatic Merge

on:
  pull_request:
    types: [opened, labeled]
    branches: [master]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Depandabot and has label
        id: check_conditions
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (github.event_name !== 'pull_request') {
              console.log('This action is triggered by events other than pull requests. Exiting.');
              return;
            }

            const pr = github.event.pull_request;
            const labels = pr.labels.map(label => label.name);
            if (pr.user.login === 'dependabot[bot]' && labels.includes('automatic-merge')) {
              console.log('Depandabot pull request with automatic-merge label detected.');
              console.log('::set-output name=should_merge::true');
              console.log(`::set-env name=PR_URL::${pr.html_url}`);
            } else {
              console.log('Not a Depandabot pull request with automatic-merge label. Exiting.');
              console.log('::set-output name=should_merge::false');
            }

      - name: Merge Pull Request
        if: steps.check_conditions.outputs.should_merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ env.PR_URL }}
        run: |
          gh pr merge --merge --auto "${PR_URL}"
