name: Automatic Merge

on:
  pull_request:
    types: [opened, labeled, synchronize]
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Depandabot and has label
        id: check_conditions
        if: github.event_name == 'pull_request' && github.event.pull_request
        run: |
          pr=$(cat "$GITHUB_EVENT_PATH" | jq -r '.pull_request')
          user=$(echo "$pr" | jq -r '.user.login')
          labels=$(echo "$pr" | jq -r '.labels[].name')
          if [ "$user" = "dependabot[bot]" ] && echo "$labels" | grep -q "automatic-merge"; then
            echo "Depandabot pull request with automatic-merge label detected."
            echo "::set-output name=should_merge::true"
            pr_url=$(echo "$pr" | jq -r '.html_url')
            echo "::set-env name=PR_URL::$pr_url"
          else
            echo "Not a Depandabot pull request with automatic-merge label. Exiting."
            echo "::set-output name=should_merge::false"
          fi

      - name: Merge Pull Request
        if: steps.check_conditions.outputs.should_merge == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ env.PR_URL }}
        run: |
          gh pr merge --merge --auto "${PR_URL}"
