env:
  NODE_VERSION: 20

on:
  workflow_dispatch:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn install
      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox
      - name: Cypress run on Edge
        uses: cypress-io/github-action@v2
        with:
          browser: edge