env:
  NODE_VERSION: 20

on:
  workflow_dispatch:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app-src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install global dependencies
        run: yarn global add concurrently
      - name: Install dependencies
        run: yarn install
      - name: Start api-mock and dev-server
        run: yarn run start &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
          browser: chrome, firefox, edge